version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/Flask-Project
hooks:
  BeforeInstall:
    - location: scripts/app_stop.sh
  AfterInstall:
    - location: Scripts/change_mode.sh
      timeout: 50
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 50
