version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/Flask-Project
hooks:
  BeforeInstall:
    - location: scripts/start_app.sh
  AfterInstall:
    - location: scripts/app_stop.sh
      timeout: 180
