version: 0.1
os: linux
files:
  - source: /
    destination: /home/ubuntu/Flask-App
hooks:
  AplicationStop:
    - location: scripts/app_stop.sh
      timeout: 100
      runas: root
  AplicationStart:
    - location: scripts/start_app.sh
      timeout: 100
      runas: ubuntu
