version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/Flask-Project
hooks:
  BeforeInstall:
    - location: scripts/start_app.sh
    - location: scripts/start_app.sh
  AfterInstall:
    - location: scripts/start_app.sh
      timeout: 180
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 3600
  ValidateService:
    - location: scripts/start_app.sh
      timeout: 3600
      runas: ubuntu
